Fixing linter issues for yml files (#182)
Co-authored-by: Alexandru Dimofte <alexandru.dimofte@intel.com>

diff --git a/.github/workflows/service-test.yml b/.github/workflows/service-test.yml
--- a/.github/workflows/service-test.yml
+++ b/.github/workflows/service-test.yml
@@ -12,42 +12,42 @@ on:
     branches:
       - main
       - release-*
-  workflow_dispatch: 
-  
+  workflow_dispatch:
+
 jobs:
   integration-smoke-test:
     permissions:
       contents: read
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout orch ci
-      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-      with:
-        ref: ${{ github.head_ref }}
-        persist-credentials: false
+      - name: Checkout orch ci
+        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
+        with:
+          ref: ${{ github.head_ref }}
+          persist-credentials: false
 
-    - name: Bootstrap CI environment
-      uses: open-edge-platform/orch-ci/.github/actions/bootstrap@e4fa54613527cfaad83ba8b625fd845a4ab8409d  # 0.1.53
-      with:
-        gh_token: ${{ secrets.SYS_ORCH_GITHUB }}
+      - name: Bootstrap CI environment
+        uses: open-edge-platform/orch-ci/.github/actions/bootstrap@e4fa54613527cfaad83ba8b625fd845a4ab8409d  # 0.1.53
+        with:
+          gh_token: ${{ secrets.SYS_ORCH_GITHUB }}
 
-    - name: Run service test
-      run: make run-service-test
+      - name: Run service test
+        run: make run-service-test
 
-    - name: Gather logs from every pod
-      if: always()
-      run: |
-        mkdir -p service-test-logs
-        for pod_and_namespace in $(kubectl get pods -A -o jsonpath='{range .items[*]}{.metadata.name}{";"}{.metadata.namespace}{"\n"}{end}'); do
-          pod=$(echo "$pod_and_namespace" | awk -F';' '{print $1}')
-          namespace=$(echo "$pod_and_namespace" | awk -F';' '{print $2}')
-          echo "Gathering logs for pod $pod in namespace $namespace"
-          kubectl logs "$pod" -n "$namespace" > "./service-test-logs/${pod}.log" || echo "Failed to get logs for $pod in namespace $namespace"
-        done
+      - name: Gather logs from every pod
+        if: always()
+        run: |
+          mkdir -p service-test-logs
+          for pod_and_namespace in $(kubectl get pods -A -o jsonpath='{range .items[*]}{.metadata.name}{";"}{.metadata.namespace}{"\n"}{end}'); do
+            pod=$(echo "$pod_and_namespace" | awk -F';' '{print $1}')
+            namespace=$(echo "$pod_and_namespace" | awk -F';' '{print $2}')
+            echo "Gathering logs for pod $pod in namespace $namespace"
+            kubectl logs "$pod" -n "$namespace" > "./service-test-logs/${pod}.log" || echo "Failed to get logs for $pod in namespace $namespace"
+          done
 
-    - name: Upload pod logs as evidence
-      if: always()
-      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
-      with:
-        name: service-test-logs
-        path: service-test-logs
+      - name: Upload pod logs as evidence
+        if: always()
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
+        with:
+          name: service-test-logs
+          path: service-test-logs
